### ISSUE TITLE
spawn ENOENT error

### ISSUE THREAD

**Issue by pierreloicq** [ngfelixl/nodeplotlib#17]
Hi, 
I put a simple test.js alone in a directory:  
> plotlib = require('nodeplotlib');
> const data = [{x: [1, 3, 4, 5], y: [3, 12, 1, 4], type: 'line'}];
> plotlib.plot(data);

then
npm install nodeplotlib
> npm WARN saveError ENOENT: no such file or directory, open '/home/pierre/testPlotLib/package.json'
> npm WARN enoent ENOENT: no such file or directory, open '/home/pierre/testPlotLib/package.json'

These lines appear here but not when I install for my project.
Then
node test.js
> (node:5472) UnhandledPromiseRejectionWarning: Error: spawn /home/pierre/testPlotLib/node_modules/nodeplotlib/dist/lib/xdg-open ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
>     at onErrorNT (internal/child_process.js:379:16)
>     at process._tickCallback (internal/process/next_tick.js:178:19)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
>     at startup (internal/bootstrap/node.js:201:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
> (node:5472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:5472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have an apache local server running, but same error when I switch it off.
Any idea ?
Thanks

**Comment by medved-nsk** [comment]
Hi, @pierreloicq 
We (with colleagues) faced the same issue (and port-related one as well).
For now we suspect it caused by https://github.com/ngfelixl/nodeplotlib/blob/master/src/server.ts#L41

**Comment by pierreloicq** [comment]
Thanks for your reply, so I guess I'll just wait for it to be restablished

**Comment by ngfelixl** [comment]
Thanks for your issue report :) I can not reproduce it myself with 0.6.1. But I guess @medved-nsk already figured it out in this PR #18 using the node env `port` variable. I will have a look at it today.

**Comment by medved-nsk** [comment]
Just for the record:
1. Actually #18 didn't solve this issue.
2. I believe it's not an issue at all but rather an expected behavior
[see my previous comment](https://github.com/ngfelixl/nodeplotlib/issues/17#issuecomment-485374061)

Though it can be turn into a feature request to run provided command (i.e. curl?) instead of xdg-open and thus make it compatible with GUI-less env (docker, ci etc).

**Comment by pierreloicq** [comment]
Thanks for you replies.
xeyes & xdg-open 'https://github.com/ngfelixl/nodeplotlib/' work properly in the basic terminal

**Comment by pierreloicq** [comment]
Seems to be a npm problem, I'll investigate it

**Comment by pierreloicq** [comment]
Just to be sure, do you think my warning messages could cause the problem ?

> npm install nodeplotlib
> npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none is installed. You must install peer dependencies yourself.
> npm WARN arbitragesoftjs@1.0.0 No repository field.
> 
> + nodeplotlib@0.6.2
> updated 1 package and audited 680 packages in 3.615s
> found 10 vulnerabilities (1 low, 9 moderate)
>   run `npm audit fix` to fix them, or `npm audit` for details
